//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InventorySystem.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html lang=&quot;en&quot; class=&quot; -webkit-&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///			&lt;link rel=&quot;apple-touch-icon&quot; type=&quot;image/png&quot; href=&quot;https://static.codepen.io/assets/favicon/apple-touch-icon-5ae1a0698dcc2402e9712f7d01ed509a57814f994c660df9f7a952f3060705ee.png&quot;&gt;
        ///				&lt;meta name=&quot;apple-mobile-web-app-title&quot; content=&quot;CodePen&quot;&gt;
        ///					&lt;link rel=&quot;shortcut icon&quot; type=&quot;image/x-icon&quot; href=&quot;https://static.codepen.io/assets/favicon/favicon-aec34940fbc1a6e787974dcd360f2c6b63348d4b1f4e06c77743096d55480f33.ico&quot;&gt;
        ///						&lt;link re [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string printTemplate {
            get {
                return ResourceManager.GetString("printTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;tr class=&quot;product&quot;&gt;
        ///	&lt;td class=&quot;product&quot;&gt;
        ///		&lt;strong&gt; ProductName &lt;/strong&gt;
        ///	&lt;/td&gt;
        ///	&lt;td class=&quot;product&quot;&gt;
        ///		&lt;strong&gt; UnitValue &lt;/strong&gt;
        ///	&lt;/td&gt;
        ///	&lt;td class=&quot;product&quot;&gt;
        ///		&lt;strong&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;/strong&gt;
        ///	&lt;/td&gt;
        ///	&lt;td class=&quot;product&quot;&gt;
        ///		&lt;strong&gt;ProductCount&lt;/strong&gt;
        ///	&lt;/td&gt;
        ///	&lt;td class=&quot;product&quot;&gt;
        ///		&lt;strong&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;/strong&gt;
        ///	&lt;/td&gt;
        ///	&lt;td class=&quot;product&quot;&gt;
        ///		&lt;strong&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;/strong&gt;
        ///	&lt;/td&gt;
        ///	&lt;td class=&quot;product&quot;&gt;
        ///		&lt;strong&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt; [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string productPart {
            get {
                return ResourceManager.GetString("productPart", resourceCulture);
            }
        }
    }
}
